//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIClient.ServiceReferenceMI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_admin", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ad_passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ad_usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ad_id {
            get {
                return this.ad_idField;
            }
            set {
                if ((this.ad_idField.Equals(value) != true)) {
                    this.ad_idField = value;
                    this.RaisePropertyChanged("ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ad_password {
            get {
                return this.ad_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.ad_passwordField, value) != true)) {
                    this.ad_passwordField = value;
                    this.RaisePropertyChanged("ad_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ad_username {
            get {
                return this.ad_usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ad_usernameField, value) != true)) {
                    this.ad_usernameField = value;
                    this.RaisePropertyChanged("ad_username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_order", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int o_cus_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime o_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime o_deli_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int o_dt_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_folderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int o_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_payField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int o_pr_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_recipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_recip_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int o_s_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_shipaddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string o_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_customer tb_customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_deliverytime tb_deliverytimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_orderdetail[] tb_orderdetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_printsize tb_printsizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_shippingcategory tb_shippingcategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int o_cus_id {
            get {
                return this.o_cus_idField;
            }
            set {
                if ((this.o_cus_idField.Equals(value) != true)) {
                    this.o_cus_idField = value;
                    this.RaisePropertyChanged("o_cus_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime o_date {
            get {
                return this.o_dateField;
            }
            set {
                if ((this.o_dateField.Equals(value) != true)) {
                    this.o_dateField = value;
                    this.RaisePropertyChanged("o_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime o_deli_date {
            get {
                return this.o_deli_dateField;
            }
            set {
                if ((this.o_deli_dateField.Equals(value) != true)) {
                    this.o_deli_dateField = value;
                    this.RaisePropertyChanged("o_deli_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int o_dt_id {
            get {
                return this.o_dt_idField;
            }
            set {
                if ((this.o_dt_idField.Equals(value) != true)) {
                    this.o_dt_idField = value;
                    this.RaisePropertyChanged("o_dt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_folder {
            get {
                return this.o_folderField;
            }
            set {
                if ((object.ReferenceEquals(this.o_folderField, value) != true)) {
                    this.o_folderField = value;
                    this.RaisePropertyChanged("o_folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int o_id {
            get {
                return this.o_idField;
            }
            set {
                if ((this.o_idField.Equals(value) != true)) {
                    this.o_idField = value;
                    this.RaisePropertyChanged("o_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_pay {
            get {
                return this.o_payField;
            }
            set {
                if ((object.ReferenceEquals(this.o_payField, value) != true)) {
                    this.o_payField = value;
                    this.RaisePropertyChanged("o_pay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int o_pr_id {
            get {
                return this.o_pr_idField;
            }
            set {
                if ((this.o_pr_idField.Equals(value) != true)) {
                    this.o_pr_idField = value;
                    this.RaisePropertyChanged("o_pr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_recip {
            get {
                return this.o_recipField;
            }
            set {
                if ((object.ReferenceEquals(this.o_recipField, value) != true)) {
                    this.o_recipField = value;
                    this.RaisePropertyChanged("o_recip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_recip_phone {
            get {
                return this.o_recip_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.o_recip_phoneField, value) != true)) {
                    this.o_recip_phoneField = value;
                    this.RaisePropertyChanged("o_recip_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int o_s_id {
            get {
                return this.o_s_idField;
            }
            set {
                if ((this.o_s_idField.Equals(value) != true)) {
                    this.o_s_idField = value;
                    this.RaisePropertyChanged("o_s_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_shipadd {
            get {
                return this.o_shipaddField;
            }
            set {
                if ((object.ReferenceEquals(this.o_shipaddField, value) != true)) {
                    this.o_shipaddField = value;
                    this.RaisePropertyChanged("o_shipadd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string o_status {
            get {
                return this.o_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.o_statusField, value) != true)) {
                    this.o_statusField = value;
                    this.RaisePropertyChanged("o_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_customer tb_customer {
            get {
                return this.tb_customerField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_customerField, value) != true)) {
                    this.tb_customerField = value;
                    this.RaisePropertyChanged("tb_customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_deliverytime tb_deliverytime {
            get {
                return this.tb_deliverytimeField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_deliverytimeField, value) != true)) {
                    this.tb_deliverytimeField = value;
                    this.RaisePropertyChanged("tb_deliverytime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_orderdetail[] tb_orderdetail {
            get {
                return this.tb_orderdetailField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderdetailField, value) != true)) {
                    this.tb_orderdetailField = value;
                    this.RaisePropertyChanged("tb_orderdetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_printsize tb_printsize {
            get {
                return this.tb_printsizeField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_printsizeField, value) != true)) {
                    this.tb_printsizeField = value;
                    this.RaisePropertyChanged("tb_printsize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_shippingcategory tb_shippingcategory {
            get {
                return this.tb_shippingcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_shippingcategoryField, value) != true)) {
                    this.tb_shippingcategoryField = value;
                    this.RaisePropertyChanged("tb_shippingcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_customer", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_addField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_cardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> cus_dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> cus_genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cus_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cus_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_order[] tb_orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_add {
            get {
                return this.cus_addField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_addField, value) != true)) {
                    this.cus_addField = value;
                    this.RaisePropertyChanged("cus_add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_card {
            get {
                return this.cus_cardField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_cardField, value) != true)) {
                    this.cus_cardField = value;
                    this.RaisePropertyChanged("cus_card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> cus_dob {
            get {
                return this.cus_dobField;
            }
            set {
                if ((this.cus_dobField.Equals(value) != true)) {
                    this.cus_dobField = value;
                    this.RaisePropertyChanged("cus_dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_email {
            get {
                return this.cus_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_emailField, value) != true)) {
                    this.cus_emailField = value;
                    this.RaisePropertyChanged("cus_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_fname {
            get {
                return this.cus_fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_fnameField, value) != true)) {
                    this.cus_fnameField = value;
                    this.RaisePropertyChanged("cus_fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> cus_gender {
            get {
                return this.cus_genderField;
            }
            set {
                if ((this.cus_genderField.Equals(value) != true)) {
                    this.cus_genderField = value;
                    this.RaisePropertyChanged("cus_gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cus_id {
            get {
                return this.cus_idField;
            }
            set {
                if ((this.cus_idField.Equals(value) != true)) {
                    this.cus_idField = value;
                    this.RaisePropertyChanged("cus_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_lname {
            get {
                return this.cus_lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_lnameField, value) != true)) {
                    this.cus_lnameField = value;
                    this.RaisePropertyChanged("cus_lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_pass {
            get {
                return this.cus_passField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_passField, value) != true)) {
                    this.cus_passField = value;
                    this.RaisePropertyChanged("cus_pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cus_phone {
            get {
                return this.cus_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.cus_phoneField, value) != true)) {
                    this.cus_phoneField = value;
                    this.RaisePropertyChanged("cus_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_order[] tb_order {
            get {
                return this.tb_orderField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderField, value) != true)) {
                    this.tb_orderField = value;
                    this.RaisePropertyChanged("tb_order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_deliverytime", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_deliverytime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dt_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dt_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dt_ratioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_order[] tb_orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dt_id {
            get {
                return this.dt_idField;
            }
            set {
                if ((this.dt_idField.Equals(value) != true)) {
                    this.dt_idField = value;
                    this.RaisePropertyChanged("dt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dt_num {
            get {
                return this.dt_numField;
            }
            set {
                if ((this.dt_numField.Equals(value) != true)) {
                    this.dt_numField = value;
                    this.RaisePropertyChanged("dt_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dt_ratio {
            get {
                return this.dt_ratioField;
            }
            set {
                if ((this.dt_ratioField.Equals(value) != true)) {
                    this.dt_ratioField = value;
                    this.RaisePropertyChanged("dt_ratio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_order[] tb_order {
            get {
                return this.tb_orderField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderField, value) != true)) {
                    this.tb_orderField = value;
                    this.RaisePropertyChanged("tb_order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_printsize", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_printsize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pr_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pr_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pr_sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_order[] tb_orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pr_id {
            get {
                return this.pr_idField;
            }
            set {
                if ((this.pr_idField.Equals(value) != true)) {
                    this.pr_idField = value;
                    this.RaisePropertyChanged("pr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pr_price {
            get {
                return this.pr_priceField;
            }
            set {
                if ((this.pr_priceField.Equals(value) != true)) {
                    this.pr_priceField = value;
                    this.RaisePropertyChanged("pr_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pr_size {
            get {
                return this.pr_sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.pr_sizeField, value) != true)) {
                    this.pr_sizeField = value;
                    this.RaisePropertyChanged("pr_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_order[] tb_order {
            get {
                return this.tb_orderField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderField, value) != true)) {
                    this.tb_orderField = value;
                    this.RaisePropertyChanged("tb_order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_shippingcategory", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_shippingcategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int s_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string s_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal s_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_order[] tb_orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int s_id {
            get {
                return this.s_idField;
            }
            set {
                if ((this.s_idField.Equals(value) != true)) {
                    this.s_idField = value;
                    this.RaisePropertyChanged("s_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string s_location {
            get {
                return this.s_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.s_locationField, value) != true)) {
                    this.s_locationField = value;
                    this.RaisePropertyChanged("s_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal s_price {
            get {
                return this.s_priceField;
            }
            set {
                if ((this.s_priceField.Equals(value) != true)) {
                    this.s_priceField = value;
                    this.RaisePropertyChanged("s_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_order[] tb_order {
            get {
                return this.tb_orderField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderField, value) != true)) {
                    this.tb_orderField = value;
                    this.RaisePropertyChanged("tb_order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_orderdetail", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_orderdetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderdetail_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderdetail_img_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderdetail_o_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_image tb_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_order tb_orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderdetail_id {
            get {
                return this.orderdetail_idField;
            }
            set {
                if ((this.orderdetail_idField.Equals(value) != true)) {
                    this.orderdetail_idField = value;
                    this.RaisePropertyChanged("orderdetail_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderdetail_img_id {
            get {
                return this.orderdetail_img_idField;
            }
            set {
                if ((this.orderdetail_img_idField.Equals(value) != true)) {
                    this.orderdetail_img_idField = value;
                    this.RaisePropertyChanged("orderdetail_img_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderdetail_o_id {
            get {
                return this.orderdetail_o_idField;
            }
            set {
                if ((this.orderdetail_o_idField.Equals(value) != true)) {
                    this.orderdetail_o_idField = value;
                    this.RaisePropertyChanged("orderdetail_o_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_image tb_image {
            get {
                return this.tb_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_imageField, value) != true)) {
                    this.tb_imageField = value;
                    this.RaisePropertyChanged("tb_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_order tb_order {
            get {
                return this.tb_orderField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderField, value) != true)) {
                    this.tb_orderField = value;
                    this.RaisePropertyChanged("tb_order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_image", Namespace="http://schemas.datacontract.org/2004/07/MyImageService")]
    [System.SerializableAttribute()]
    public partial class tb_image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int img_copiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int img_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string img_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string img_sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MIClient.ServiceReferenceMI.tb_orderdetail[] tb_orderdetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int img_copies {
            get {
                return this.img_copiesField;
            }
            set {
                if ((this.img_copiesField.Equals(value) != true)) {
                    this.img_copiesField = value;
                    this.RaisePropertyChanged("img_copies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int img_id {
            get {
                return this.img_idField;
            }
            set {
                if ((this.img_idField.Equals(value) != true)) {
                    this.img_idField = value;
                    this.RaisePropertyChanged("img_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_link {
            get {
                return this.img_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.img_linkField, value) != true)) {
                    this.img_linkField = value;
                    this.RaisePropertyChanged("img_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_size {
            get {
                return this.img_sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.img_sizeField, value) != true)) {
                    this.img_sizeField = value;
                    this.RaisePropertyChanged("img_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIClient.ServiceReferenceMI.tb_orderdetail[] tb_orderdetail {
            get {
                return this.tb_orderdetailField;
            }
            set {
                if ((object.ReferenceEquals(this.tb_orderdetailField, value) != true)) {
                    this.tb_orderdetailField = value;
                    this.RaisePropertyChanged("tb_orderdetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMI.IServiceMI")]
    public interface IServiceMI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/AdminLogin", ReplyAction="http://tempuri.org/IServiceMI/AdminLoginResponse")]
        bool AdminLogin(string uid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/AdminLogin", ReplyAction="http://tempuri.org/IServiceMI/AdminLoginResponse")]
        System.Threading.Tasks.Task<bool> AdminLoginAsync(string uid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetAdmins", ReplyAction="http://tempuri.org/IServiceMI/GetAdminsResponse")]
        MIClient.ServiceReferenceMI.tb_admin[] GetAdmins(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetAdmins", ReplyAction="http://tempuri.org/IServiceMI/GetAdminsResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_admin[]> GetAdminsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrders", ReplyAction="http://tempuri.org/IServiceMI/GetOrdersResponse")]
        MIClient.ServiceReferenceMI.tb_order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrders", ReplyAction="http://tempuri.org/IServiceMI/GetOrdersResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOneOrders", ReplyAction="http://tempuri.org/IServiceMI/GetOneOrdersResponse")]
        MIClient.ServiceReferenceMI.tb_order GetOneOrders(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOneOrders", ReplyAction="http://tempuri.org/IServiceMI/GetOneOrdersResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order> GetOneOrdersAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/UpdateStatus", ReplyAction="http://tempuri.org/IServiceMI/UpdateStatusResponse")]
        void UpdateStatus(MIClient.ServiceReferenceMI.tb_order upStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/UpdateStatus", ReplyAction="http://tempuri.org/IServiceMI/UpdateStatusResponse")]
        System.Threading.Tasks.Task UpdateStatusAsync(MIClient.ServiceReferenceMI.tb_order upStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ClearData", ReplyAction="http://tempuri.org/IServiceMI/ClearDataResponse")]
        void ClearData(int orderID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ClearData", ReplyAction="http://tempuri.org/IServiceMI/ClearDataResponse")]
        System.Threading.Tasks.Task ClearDataAsync(int orderID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrdersByStatus", ReplyAction="http://tempuri.org/IServiceMI/GetOrdersByStatusResponse")]
        MIClient.ServiceReferenceMI.tb_order[] GetOrdersByStatus(string stt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrdersByStatus", ReplyAction="http://tempuri.org/IServiceMI/GetOrdersByStatusResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrdersByStatusAsync(string stt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrderNotFinished", ReplyAction="http://tempuri.org/IServiceMI/GetOrderNotFinishedResponse")]
        MIClient.ServiceReferenceMI.tb_order[] GetOrderNotFinished();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOrderNotFinished", ReplyAction="http://tempuri.org/IServiceMI/GetOrderNotFinishedResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrderNotFinishedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetCustomers", ReplyAction="http://tempuri.org/IServiceMI/GetCustomersResponse")]
        MIClient.ServiceReferenceMI.tb_customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetCustomers", ReplyAction="http://tempuri.org/IServiceMI/GetCustomersResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_customer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SearchCustomerByName", ReplyAction="http://tempuri.org/IServiceMI/SearchCustomerByNameResponse")]
        MIClient.ServiceReferenceMI.tb_customer[] SearchCustomerByName(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SearchCustomerByName", ReplyAction="http://tempuri.org/IServiceMI/SearchCustomerByNameResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_customer[]> SearchCustomerByNameAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CountAllCustomer", ReplyAction="http://tempuri.org/IServiceMI/CountAllCustomerResponse")]
        int CountAllCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CountAllCustomer", ReplyAction="http://tempuri.org/IServiceMI/CountAllCustomerResponse")]
        System.Threading.Tasks.Task<int> CountAllCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetPrintsizes", ReplyAction="http://tempuri.org/IServiceMI/GetPrintsizesResponse")]
        MIClient.ServiceReferenceMI.tb_printsize[] GetPrintsizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetPrintsizes", ReplyAction="http://tempuri.org/IServiceMI/GetPrintsizesResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize[]> GetPrintsizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOnePrintsize", ReplyAction="http://tempuri.org/IServiceMI/GetOnePrintsizeResponse")]
        MIClient.ServiceReferenceMI.tb_printsize GetOnePrintsize(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetOnePrintsize", ReplyAction="http://tempuri.org/IServiceMI/GetOnePrintsizeResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize> GetOnePrintsizeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreatePrintsizes", ReplyAction="http://tempuri.org/IServiceMI/CreatePrintsizesResponse")]
        void CreatePrintsizes(MIClient.ServiceReferenceMI.tb_printsize newSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreatePrintsizes", ReplyAction="http://tempuri.org/IServiceMI/CreatePrintsizesResponse")]
        System.Threading.Tasks.Task CreatePrintsizesAsync(MIClient.ServiceReferenceMI.tb_printsize newSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/DeletePrintsizes", ReplyAction="http://tempuri.org/IServiceMI/DeletePrintsizesResponse")]
        void DeletePrintsizes(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/DeletePrintsizes", ReplyAction="http://tempuri.org/IServiceMI/DeletePrintsizesResponse")]
        System.Threading.Tasks.Task DeletePrintsizesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/UpdatePrintsize", ReplyAction="http://tempuri.org/IServiceMI/UpdatePrintsizeResponse")]
        void UpdatePrintsize(MIClient.ServiceReferenceMI.tb_printsize updateSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/UpdatePrintsize", ReplyAction="http://tempuri.org/IServiceMI/UpdatePrintsizeResponse")]
        System.Threading.Tasks.Task UpdatePrintsizeAsync(MIClient.ServiceReferenceMI.tb_printsize updateSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ValidatePrintSize", ReplyAction="http://tempuri.org/IServiceMI/ValidatePrintSizeResponse")]
        bool ValidatePrintSize(MIClient.ServiceReferenceMI.tb_printsize valsize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ValidatePrintSize", ReplyAction="http://tempuri.org/IServiceMI/ValidatePrintSizeResponse")]
        System.Threading.Tasks.Task<bool> ValidatePrintSizeAsync(MIClient.ServiceReferenceMI.tb_printsize valsize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SearchPrintSizebyName", ReplyAction="http://tempuri.org/IServiceMI/SearchPrintSizebyNameResponse")]
        MIClient.ServiceReferenceMI.tb_printsize[] SearchPrintSizebyName(string size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SearchPrintSizebyName", ReplyAction="http://tempuri.org/IServiceMI/SearchPrintSizebyNameResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize[]> SearchPrintSizebyNameAsync(string size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetCustomer", ReplyAction="http://tempuri.org/IServiceMI/GetCustomerResponse")]
        MIData.Models.Customer GetCustomer(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetCustomer", ReplyAction="http://tempuri.org/IServiceMI/GetCustomerResponse")]
        System.Threading.Tasks.Task<MIData.Models.Customer> GetCustomerAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/FindCustomer", ReplyAction="http://tempuri.org/IServiceMI/FindCustomerResponse")]
        MIData.Models.Customer FindCustomer(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/FindCustomer", ReplyAction="http://tempuri.org/IServiceMI/FindCustomerResponse")]
        System.Threading.Tasks.Task<MIData.Models.Customer> FindCustomerAsync(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreateCustomer", ReplyAction="http://tempuri.org/IServiceMI/CreateCustomerResponse")]
        string CreateCustomer(MIData.Models.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreateCustomer", ReplyAction="http://tempuri.org/IServiceMI/CreateCustomerResponse")]
        System.Threading.Tasks.Task<string> CreateCustomerAsync(MIData.Models.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/EditCustomer", ReplyAction="http://tempuri.org/IServiceMI/EditCustomerResponse")]
        void EditCustomer(MIData.Models.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/EditCustomer", ReplyAction="http://tempuri.org/IServiceMI/EditCustomerResponse")]
        System.Threading.Tasks.Task EditCustomerAsync(MIData.Models.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/Login", ReplyAction="http://tempuri.org/IServiceMI/LoginResponse")]
        bool Login(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/Login", ReplyAction="http://tempuri.org/IServiceMI/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/Logout", ReplyAction="http://tempuri.org/IServiceMI/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/Logout", ReplyAction="http://tempuri.org/IServiceMI/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/FindOrders", ReplyAction="http://tempuri.org/IServiceMI/FindOrdersResponse")]
        MIData.Models.FollowedOrder[] FindOrders(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/FindOrders", ReplyAction="http://tempuri.org/IServiceMI/FindOrdersResponse")]
        System.Threading.Tasks.Task<MIData.Models.FollowedOrder[]> FindOrdersAsync(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreateOrder", ReplyAction="http://tempuri.org/IServiceMI/CreateOrderResponse")]
        int CreateOrder(int custID, string folder, MIData.Models.Recipient recipient, MIData.Models.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CreateOrder", ReplyAction="http://tempuri.org/IServiceMI/CreateOrderResponse")]
        System.Threading.Tasks.Task<int> CreateOrderAsync(int custID, string folder, MIData.Models.Recipient recipient, MIData.Models.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveDetailImage", ReplyAction="http://tempuri.org/IServiceMI/SaveDetailImageResponse")]
        void SaveDetailImage(MIData.Models.MImages mImages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveDetailImage", ReplyAction="http://tempuri.org/IServiceMI/SaveDetailImageResponse")]
        System.Threading.Tasks.Task SaveDetailImageAsync(MIData.Models.MImages mImages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveOrderDetail", ReplyAction="http://tempuri.org/IServiceMI/SaveOrderDetailResponse")]
        void SaveOrderDetail(int orderID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveOrderDetail", ReplyAction="http://tempuri.org/IServiceMI/SaveOrderDetailResponse")]
        System.Threading.Tasks.Task SaveOrderDetailAsync(int orderID, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/RandomFolder", ReplyAction="http://tempuri.org/IServiceMI/RandomFolderResponse")]
        string RandomFolder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/RandomFolder", ReplyAction="http://tempuri.org/IServiceMI/RandomFolderResponse")]
        System.Threading.Tasks.Task<string> RandomFolderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveImages", ReplyAction="http://tempuri.org/IServiceMI/SaveImagesResponse")]
        MIData.Models.MImages SaveImages(System.Web.HttpPostedFileBase[] images, string dir, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/SaveImages", ReplyAction="http://tempuri.org/IServiceMI/SaveImagesResponse")]
        System.Threading.Tasks.Task<MIData.Models.MImages> SaveImagesAsync(System.Web.HttpPostedFileBase[] images, string dir, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetSize", ReplyAction="http://tempuri.org/IServiceMI/GetSizeResponse")]
        string[] GetSize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetSize", ReplyAction="http://tempuri.org/IServiceMI/GetSizeResponse")]
        System.Threading.Tasks.Task<string[]> GetSizeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ValidateDeliDate", ReplyAction="http://tempuri.org/IServiceMI/ValidateDeliDateResponse")]
        string ValidateDeliDate(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/ValidateDeliDate", ReplyAction="http://tempuri.org/IServiceMI/ValidateDeliDateResponse")]
        System.Threading.Tasks.Task<string> ValidateDeliDateAsync(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetShipCate", ReplyAction="http://tempuri.org/IServiceMI/GetShipCateResponse")]
        MIClient.ServiceReferenceMI.tb_shippingcategory GetShipCate(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetShipCate", ReplyAction="http://tempuri.org/IServiceMI/GetShipCateResponse")]
        System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_shippingcategory> GetShipCateAsync(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetShipList", ReplyAction="http://tempuri.org/IServiceMI/GetShipListResponse")]
        string[] GetShipList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetShipList", ReplyAction="http://tempuri.org/IServiceMI/GetShipListResponse")]
        System.Threading.Tasks.Task<string[]> GetShipListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetDeliveryRatio", ReplyAction="http://tempuri.org/IServiceMI/GetDeliveryRatioResponse")]
        double GetDeliveryRatio(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetDeliveryRatio", ReplyAction="http://tempuri.org/IServiceMI/GetDeliveryRatioResponse")]
        System.Threading.Tasks.Task<double> GetDeliveryRatioAsync(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetDeliveryID", ReplyAction="http://tempuri.org/IServiceMI/GetDeliveryIDResponse")]
        int GetDeliveryID(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/GetDeliveryID", ReplyAction="http://tempuri.org/IServiceMI/GetDeliveryIDResponse")]
        System.Threading.Tasks.Task<int> GetDeliveryIDAsync(System.DateTime deliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CalculateImage", ReplyAction="http://tempuri.org/IServiceMI/CalculateImageResponse")]
        MIData.Models.MImages CalculateImage(MIData.Models.MImages mImages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CalculateImage", ReplyAction="http://tempuri.org/IServiceMI/CalculateImageResponse")]
        System.Threading.Tasks.Task<MIData.Models.MImages> CalculateImageAsync(MIData.Models.MImages mImages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CalculateShip", ReplyAction="http://tempuri.org/IServiceMI/CalculateShipResponse")]
        decimal CalculateShip(MIData.Models.Recipient recipient, decimal imgTotal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/CalculateShip", ReplyAction="http://tempuri.org/IServiceMI/CalculateShipResponse")]
        System.Threading.Tasks.Task<decimal> CalculateShipAsync(MIData.Models.Recipient recipient, decimal imgTotal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/AddCreditCard", ReplyAction="http://tempuri.org/IServiceMI/AddCreditCardResponse")]
        void AddCreditCard(int custID, string custCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/AddCreditCard", ReplyAction="http://tempuri.org/IServiceMI/AddCreditCardResponse")]
        System.Threading.Tasks.Task AddCreditCardAsync(int custID, string custCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/VerifyCreditCard", ReplyAction="http://tempuri.org/IServiceMI/VerifyCreditCardResponse")]
        string VerifyCreditCard(int custID, System.DateTime expiredDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMI/VerifyCreditCard", ReplyAction="http://tempuri.org/IServiceMI/VerifyCreditCardResponse")]
        System.Threading.Tasks.Task<string> VerifyCreditCardAsync(int custID, System.DateTime expiredDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMIChannel : MIClient.ServiceReferenceMI.IServiceMI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMIClient : System.ServiceModel.ClientBase<MIClient.ServiceReferenceMI.IServiceMI>, MIClient.ServiceReferenceMI.IServiceMI {
        
        public ServiceMIClient() {
        }
        
        public ServiceMIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AdminLogin(string uid, string pwd) {
            return base.Channel.AdminLogin(uid, pwd);
        }
        
        public System.Threading.Tasks.Task<bool> AdminLoginAsync(string uid, string pwd) {
            return base.Channel.AdminLoginAsync(uid, pwd);
        }
        
        public MIClient.ServiceReferenceMI.tb_admin[] GetAdmins(string username) {
            return base.Channel.GetAdmins(username);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_admin[]> GetAdminsAsync(string username) {
            return base.Channel.GetAdminsAsync(username);
        }
        
        public MIClient.ServiceReferenceMI.tb_order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public MIClient.ServiceReferenceMI.tb_order GetOneOrders(int id) {
            return base.Channel.GetOneOrders(id);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order> GetOneOrdersAsync(int id) {
            return base.Channel.GetOneOrdersAsync(id);
        }
        
        public void UpdateStatus(MIClient.ServiceReferenceMI.tb_order upStatus) {
            base.Channel.UpdateStatus(upStatus);
        }
        
        public System.Threading.Tasks.Task UpdateStatusAsync(MIClient.ServiceReferenceMI.tb_order upStatus) {
            return base.Channel.UpdateStatusAsync(upStatus);
        }
        
        public void ClearData(int orderID, string folder) {
            base.Channel.ClearData(orderID, folder);
        }
        
        public System.Threading.Tasks.Task ClearDataAsync(int orderID, string folder) {
            return base.Channel.ClearDataAsync(orderID, folder);
        }
        
        public MIClient.ServiceReferenceMI.tb_order[] GetOrdersByStatus(string stt) {
            return base.Channel.GetOrdersByStatus(stt);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrdersByStatusAsync(string stt) {
            return base.Channel.GetOrdersByStatusAsync(stt);
        }
        
        public MIClient.ServiceReferenceMI.tb_order[] GetOrderNotFinished() {
            return base.Channel.GetOrderNotFinished();
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_order[]> GetOrderNotFinishedAsync() {
            return base.Channel.GetOrderNotFinishedAsync();
        }
        
        public MIClient.ServiceReferenceMI.tb_customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public MIClient.ServiceReferenceMI.tb_customer[] SearchCustomerByName(string search) {
            return base.Channel.SearchCustomerByName(search);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_customer[]> SearchCustomerByNameAsync(string search) {
            return base.Channel.SearchCustomerByNameAsync(search);
        }
        
        public int CountAllCustomer() {
            return base.Channel.CountAllCustomer();
        }
        
        public System.Threading.Tasks.Task<int> CountAllCustomerAsync() {
            return base.Channel.CountAllCustomerAsync();
        }
        
        public MIClient.ServiceReferenceMI.tb_printsize[] GetPrintsizes() {
            return base.Channel.GetPrintsizes();
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize[]> GetPrintsizesAsync() {
            return base.Channel.GetPrintsizesAsync();
        }
        
        public MIClient.ServiceReferenceMI.tb_printsize GetOnePrintsize(int id) {
            return base.Channel.GetOnePrintsize(id);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize> GetOnePrintsizeAsync(int id) {
            return base.Channel.GetOnePrintsizeAsync(id);
        }
        
        public void CreatePrintsizes(MIClient.ServiceReferenceMI.tb_printsize newSize) {
            base.Channel.CreatePrintsizes(newSize);
        }
        
        public System.Threading.Tasks.Task CreatePrintsizesAsync(MIClient.ServiceReferenceMI.tb_printsize newSize) {
            return base.Channel.CreatePrintsizesAsync(newSize);
        }
        
        public void DeletePrintsizes(int id) {
            base.Channel.DeletePrintsizes(id);
        }
        
        public System.Threading.Tasks.Task DeletePrintsizesAsync(int id) {
            return base.Channel.DeletePrintsizesAsync(id);
        }
        
        public void UpdatePrintsize(MIClient.ServiceReferenceMI.tb_printsize updateSize) {
            base.Channel.UpdatePrintsize(updateSize);
        }
        
        public System.Threading.Tasks.Task UpdatePrintsizeAsync(MIClient.ServiceReferenceMI.tb_printsize updateSize) {
            return base.Channel.UpdatePrintsizeAsync(updateSize);
        }
        
        public bool ValidatePrintSize(MIClient.ServiceReferenceMI.tb_printsize valsize) {
            return base.Channel.ValidatePrintSize(valsize);
        }
        
        public System.Threading.Tasks.Task<bool> ValidatePrintSizeAsync(MIClient.ServiceReferenceMI.tb_printsize valsize) {
            return base.Channel.ValidatePrintSizeAsync(valsize);
        }
        
        public MIClient.ServiceReferenceMI.tb_printsize[] SearchPrintSizebyName(string size) {
            return base.Channel.SearchPrintSizebyName(size);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_printsize[]> SearchPrintSizebyNameAsync(string size) {
            return base.Channel.SearchPrintSizebyNameAsync(size);
        }
        
        public MIData.Models.Customer GetCustomer(string email) {
            return base.Channel.GetCustomer(email);
        }
        
        public System.Threading.Tasks.Task<MIData.Models.Customer> GetCustomerAsync(string email) {
            return base.Channel.GetCustomerAsync(email);
        }
        
        public MIData.Models.Customer FindCustomer(int custID) {
            return base.Channel.FindCustomer(custID);
        }
        
        public System.Threading.Tasks.Task<MIData.Models.Customer> FindCustomerAsync(int custID) {
            return base.Channel.FindCustomerAsync(custID);
        }
        
        public string CreateCustomer(MIData.Models.Customer customer) {
            return base.Channel.CreateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<string> CreateCustomerAsync(MIData.Models.Customer customer) {
            return base.Channel.CreateCustomerAsync(customer);
        }
        
        public void EditCustomer(MIData.Models.Customer customer) {
            base.Channel.EditCustomer(customer);
        }
        
        public System.Threading.Tasks.Task EditCustomerAsync(MIData.Models.Customer customer) {
            return base.Channel.EditCustomerAsync(customer);
        }
        
        public bool Login(string email, string pass) {
            return base.Channel.Login(email, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string pass) {
            return base.Channel.LoginAsync(email, pass);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public MIData.Models.FollowedOrder[] FindOrders(int custID) {
            return base.Channel.FindOrders(custID);
        }
        
        public System.Threading.Tasks.Task<MIData.Models.FollowedOrder[]> FindOrdersAsync(int custID) {
            return base.Channel.FindOrdersAsync(custID);
        }
        
        public int CreateOrder(int custID, string folder, MIData.Models.Recipient recipient, MIData.Models.Payment payment) {
            return base.Channel.CreateOrder(custID, folder, recipient, payment);
        }
        
        public System.Threading.Tasks.Task<int> CreateOrderAsync(int custID, string folder, MIData.Models.Recipient recipient, MIData.Models.Payment payment) {
            return base.Channel.CreateOrderAsync(custID, folder, recipient, payment);
        }
        
        public void SaveDetailImage(MIData.Models.MImages mImages) {
            base.Channel.SaveDetailImage(mImages);
        }
        
        public System.Threading.Tasks.Task SaveDetailImageAsync(MIData.Models.MImages mImages) {
            return base.Channel.SaveDetailImageAsync(mImages);
        }
        
        public void SaveOrderDetail(int orderID, string folder) {
            base.Channel.SaveOrderDetail(orderID, folder);
        }
        
        public System.Threading.Tasks.Task SaveOrderDetailAsync(int orderID, string folder) {
            return base.Channel.SaveOrderDetailAsync(orderID, folder);
        }
        
        public string RandomFolder() {
            return base.Channel.RandomFolder();
        }
        
        public System.Threading.Tasks.Task<string> RandomFolderAsync() {
            return base.Channel.RandomFolderAsync();
        }
        
        public MIData.Models.MImages SaveImages(System.Web.HttpPostedFileBase[] images, string dir, string folder) {
            return base.Channel.SaveImages(images, dir, folder);
        }
        
        public System.Threading.Tasks.Task<MIData.Models.MImages> SaveImagesAsync(System.Web.HttpPostedFileBase[] images, string dir, string folder) {
            return base.Channel.SaveImagesAsync(images, dir, folder);
        }
        
        public string[] GetSize() {
            return base.Channel.GetSize();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSizeAsync() {
            return base.Channel.GetSizeAsync();
        }
        
        public string ValidateDeliDate(System.DateTime deliveryDate) {
            return base.Channel.ValidateDeliDate(deliveryDate);
        }
        
        public System.Threading.Tasks.Task<string> ValidateDeliDateAsync(System.DateTime deliveryDate) {
            return base.Channel.ValidateDeliDateAsync(deliveryDate);
        }
        
        public MIClient.ServiceReferenceMI.tb_shippingcategory GetShipCate(string location) {
            return base.Channel.GetShipCate(location);
        }
        
        public System.Threading.Tasks.Task<MIClient.ServiceReferenceMI.tb_shippingcategory> GetShipCateAsync(string location) {
            return base.Channel.GetShipCateAsync(location);
        }
        
        public string[] GetShipList() {
            return base.Channel.GetShipList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetShipListAsync() {
            return base.Channel.GetShipListAsync();
        }
        
        public double GetDeliveryRatio(System.DateTime deliveryDate) {
            return base.Channel.GetDeliveryRatio(deliveryDate);
        }
        
        public System.Threading.Tasks.Task<double> GetDeliveryRatioAsync(System.DateTime deliveryDate) {
            return base.Channel.GetDeliveryRatioAsync(deliveryDate);
        }
        
        public int GetDeliveryID(System.DateTime deliveryDate) {
            return base.Channel.GetDeliveryID(deliveryDate);
        }
        
        public System.Threading.Tasks.Task<int> GetDeliveryIDAsync(System.DateTime deliveryDate) {
            return base.Channel.GetDeliveryIDAsync(deliveryDate);
        }
        
        public MIData.Models.MImages CalculateImage(MIData.Models.MImages mImages) {
            return base.Channel.CalculateImage(mImages);
        }
        
        public System.Threading.Tasks.Task<MIData.Models.MImages> CalculateImageAsync(MIData.Models.MImages mImages) {
            return base.Channel.CalculateImageAsync(mImages);
        }
        
        public decimal CalculateShip(MIData.Models.Recipient recipient, decimal imgTotal) {
            return base.Channel.CalculateShip(recipient, imgTotal);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateShipAsync(MIData.Models.Recipient recipient, decimal imgTotal) {
            return base.Channel.CalculateShipAsync(recipient, imgTotal);
        }
        
        public void AddCreditCard(int custID, string custCard) {
            base.Channel.AddCreditCard(custID, custCard);
        }
        
        public System.Threading.Tasks.Task AddCreditCardAsync(int custID, string custCard) {
            return base.Channel.AddCreditCardAsync(custID, custCard);
        }
        
        public string VerifyCreditCard(int custID, System.DateTime expiredDate) {
            return base.Channel.VerifyCreditCard(custID, expiredDate);
        }
        
        public System.Threading.Tasks.Task<string> VerifyCreditCardAsync(int custID, System.DateTime expiredDate) {
            return base.Channel.VerifyCreditCardAsync(custID, expiredDate);
        }
    }
}
